##############################################################################
# Reverse Proxy
##############################################################################
FROM nginx:alpine

ADD conf.d/ /etc/nginx/conf.d
ADD index.html /etc/nginx/html/
ADD 50x.html /etc/nginx/html/
ADD 50x.json /etc/nginx/html/
