name: Console [Old] - Docker Image CI
on:
  push:
    branches: [ yntraa-onboarding ]
    paths: 
    - 'console/**'
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PWD
    - name: Prepare image tag
      run: echo "TAG=$(date +'%F-%H-%M-%S')" >> $GITHUB_ENV    
    - name: Build docker image for console
      run: docker build console/. --file console/Dockerfile --tag build/yntraa_console:${{ env.TAG }}
    - name: Push the docker image
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
      run: |
        docker tag build/yntraa_console:${{ env.TAG }} coredgeio/console:latest
        
        docker push coredgeio/console:latest
