# name: Docker Image CI
# on:
#   push:
#     branches: [ main ]
# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#     - uses: actions/checkout@v2
#     - name: Login to docker hub
#       env:
#         DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
#         DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
#       run: docker login -u $DOCKER_USER -p $DOCKER_PWD
#     - name: Prepare image tag
#       run: echo "TAG=$(date +'%F-%H-%M-%S')" >> $GITHUB_ENV
#     - name: Build docker image for console
#       run: docker build console/. --file console/Dockerfile --tag build/yntraa_console:${{ env.TAG }}
#     - name: Build docker image for admin-console
#       run: docker build admin-console/. --file admin-console/Dockerfile --tag build/yntraa_admin_console:${{ env.TAG }}
#     - name: Build docker image for yntraa platform
#       run: docker build yntraa-platform/. --file yntraa-platform/Dockerfile --tag build/yntraa_platform:${{ env.TAG }}
#     - name: Build docker image for yntraa admin platform
#       run: docker build yntraa-admin-platform/. --file yntraa-admin-platform/Dockerfile --tag build/yntraa_admin_platform:${{ env.TAG }}
#     - name: Build docker image for socketio
#       run: docker build socketio/. --file socketio/Dockerfile --tag build/socketio_sso:${{ env.TAG }}      
#     - name: Push the docker image
#       env:
#         DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
#         DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
#       run: |
#         docker tag build/yntraa_console:${{ env.TAG }} coredgeio/yntraa_console:${{ env.TAG }}
#         docker tag build/yntraa_console:${{ env.TAG }} coredgeio/yntraa_console:latest
        
#         docker tag build/yntraa_admin_console:${{ env.TAG }} coredgeio/yntraa_admin_console:${{ env.TAG }}
#         docker tag build/yntraa_admin_console:${{ env.TAG }} coredgeio/yntraa_admin_console:latest
        
#         docker tag build/yntraa_platform:${{ env.TAG }} coredgeio/yntraa_platform:${{ env.TAG }}
#         docker tag build/yntraa_platform:${{ env.TAG }} coredgeio/yntraa_platform:latest
        
#         docker tag build/yntraa_admin_platform:${{ env.TAG }} coredgeio/yntraa_admin_platform:${{ env.TAG }}
#         docker tag build/yntraa_admin_platform:${{ env.TAG }} coredgeio/yntraa_admin_platform:latest
        
#         docker tag build/socketio_sso:${{ env.TAG }} coredgeio/socketio_sso:${{ env.TAG }}
#         docker tag build/socketio_sso:${{ env.TAG }} coredgeio/socketio_sso:latest
        
        
#         docker push coredgeio/yntraa_console:${{ env.TAG }}
#         docker push coredgeio/yntraa_console:latest
        
#         docker push coredgeio/yntraa_admin_console:${{ env.TAG }}
#         docker push coredgeio/yntraa_admin_console:latest
        
#         docker push coredgeio/yntraa_platform:${{ env.TAG }}
#         docker push coredgeio/yntraa_platform:latest
        
#         docker push coredgeio/yntraa_admin_platform:${{ env.TAG }}
#         docker push coredgeio/yntraa_admin_platform:latest
        
#         docker push coredgeio/socketio_sso:${{ env.TAG }}
#         docker push coredgeio/socketio_sso:latest
